AWSTemplateFormatVersion: 2010-09-09

Description: "MySQL RDS"

Parameters:
  env:
    Type: "String"
    Description: Environment name. (dev/qa/prod)
    Default: "dev"
  DBPassword:
    NoEcho: "true"
    Description: Password MySQL database access
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.

Resources:
  #  TopicPolicy:
  #    Type: AWS::SNS::TopicPolicy
  #    Properties:
  #      PolicyDocument:
  #        Id: __dataIngestPipelineErrorTopic_basic_policy_ID
  #        Version: '2012-10-17'
  #        Statement:
  #        - Sid: __dataIngestPipelineErrorTopic_basic_policy_ID
  #          Effect: Allow
  #          Principal:
  #            Service: sts.amazonaws.com
  #          Action:
  #            - sns:GetTopicAttributes
  #            - sns:Subscribe
  #            - sns:ListSubscriptionsByTopic
  #            - sns:Publish
  #          Condition:
  #            ArnLike:
  #              aws:SourceArn: !Sub "arn:aws:sts::${AWS::AccountId}:assumed-role/ThanosRegRoleTemplate-IamRoleExtractor-*/optimizador-dataset"
  #          Resource: !Sub "arn:aws:sns::${AWS::Region}:${AWS::AccountId}:data-ingestion-pipeline-error-${env}"
  #      Topics:
  #      - !Ref dataIngestPipelineErrorTopic

  MySQLRdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      AvailabilityZone: "us-east-1a"
      #CharacterSetName: 'utf8mb4'
      DBInstanceClass: "db.m5.large"
      DBInstanceIdentifier: !Sub "mysql-thanos-${env}"
      #DBName: String
      DBParameterGroupName: "default.mysql8.0"
      DBSubnetGroupName: "default-vpc-05aacd6afb0ad3148"
      DeleteAutomatedBackups: "false"
      DeletionProtection: "false"
      EnableCloudwatchLogsExports:
        - "audit"
        - "error"
        - "slowquery"
      Engine: "mysql"
      EngineVersion: "8.0.28"
      LicenseModel: "general-public-license"
      MasterUsername: "admin"
      MasterUserPassword: !Ref DBPassword
      OptionGroupName: "default:mysql-8-0"
      Port: "3306"
      PreferredMaintenanceWindow: "sat:10:30-sat:11:00"
      #ProcessorFeatures:
      #  - ProcessorFeature
      PubliclyAccessible: "false"
      #StorageEncrypted: Boolean
      StorageType: "gp2"
      VPCSecurityGroups:
        - "sg-063dde36866c4efb7"

#####################################
#Cognito Pool
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: !Sub "SSOAzureAD-${env}"
    UsernameConfiguration:
      CaseSensitive: false
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireSymbols: true
        RequireUppercase: true
        TemporaryPasswordValidityDays: 7
    UsernameAttributes:
      - email
    MfaConfiguration: "OFF"
    Schema:
      - AttributeDataType: String
        DeveloperOnlyAttribute: false
        Mutable: true
        Name: email
#####################################
AWSTemplateFormatVersion: 2010-09-09

Description: "Cloudfront Thanos Regional"

Parameters:
  env:
    Type: "String"
    Description: Environment name. (dev/qa/prod)
    Default: "dev"
  IsoCountryCode:
    Type: "String"
    Description: ISO 3166-1 alpha-2 country code. (ar/cl/py/etc.)
    Default: "py"  

Resources:
  OriginAccessId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${IsoCountryCode}-${env} s3's OAI"

  cloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
          #Aliases: 
          #  - String
          #CacheBehaviors: 
          DefaultCacheBehavior:
            AllowedMethods: 
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            #CachedMethods: 
            #  - String
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
            #Compress: Boolean
            #FieldLevelEncryptionId: String
            #FunctionAssociations: 
            #  - FunctionAssociation
            #LambdaFunctionAssociations: 
            #  - LambdaFunctionAssociation
            #OriginRequestPolicyId: String
            #RealtimeLogConfigArn: String
            #ResponseHeadersPolicyId: String
            TargetOriginId: !Sub "front-${IsoCountryCode}-thanos-reg-${env}"
            #TrustedKeyGroups: 
            #  - String
            #TrustedSigners: 
            #  - String
            ViewerProtocolPolicy: "allow-all"
          Comment: !Sub "Main Cloudfront Distribution - ${IsoCountryCode}-thanos-reg-${env}"
          #CustomErrorResponses: 
          #  - CustomErrorResponse
          #DefaultCacheBehavior: 
          #  DefaultCacheBehavior
          DefaultRootObject: "index.html"
          Enabled: "true"
          #HttpVersion: String
          IPV6Enabled: "false"
          #Logging: 
          #  Logging
          #OriginGroups: 
          #  OriginGroups
          Origins:
            - S3OriginConfig:
                OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessId}"
              Id: !Sub "front-${IsoCountryCode}-thanos-reg-${env}"
              #ConnectionAttempts: Integer
              #ConnectionTimeout: Integer
              DomainName: !Sub "front-${IsoCountryCode}-thanos-reg-${env}.s3.${AWS::Region}.amazonaws.com"
              
              #OriginCustomHeaders: 
              #  - OriginCustomHeader
              #OriginPath: String
              #OriginShield: 
              #  OriginShield
                
            #  - CustomOriginConfig:
            #      #HTTPPort: Integer
            #      #HTTPSPort: Integer
            #      #OriginKeepaliveTimeout: Integer
            #      OriginProtocolPolicy: "match-viewer"
            #      #OriginReadTimeout: Integer
            #      OriginSSLProtocols: 
            #        - "SSLv3"
              
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub "front-${IsoCountryCode}-thanos-reg-${env}/*"
      PolicyDocument:
        Id: !Sub "PolicyForCloudFrontPrivateContent-front-${IsoCountryCode}-thanos-reg-${env}"
        Statement:
        - Sid: '1'
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessId}"
          Action: s3:GetObject
          Resource: !Sub "arn:aws:s3:::front-${IsoCountryCode}-thanos-reg-${env}/*"