AWSTemplateFormatVersion: 2010-09-09
Description: RDS

Parameters:
  env:
    Type: "String"
    Description: Environment name. (dev/qa/prod/cbo)
    Default: "dev"
  DBPassword:
    Type: "String"
    Description: Password BD
    Default: "ASD123ASD"
  networkStackName:
    Type: "String"
    Description: networkStackName
    Default: "vpc-devregional-thanos"

Resources:
  MySQLRdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "40"
      AvailabilityZone: "us-east-1a"
      DBInstanceClass: "db.m5.large"
      DBInstanceIdentifier: !Sub "thanos-regional-${env}"
      DBName: "thanos-regional"
      DBParameterGroupName: "default.mysql8.0"
      DBSubnetGroupName: "default-vpc-05aacd6afb0ad3148"
      DeleteAutomatedBackups: "false"
      DeletionProtection: "false"
      EnableCloudwatchLogsExports:
        - "audit"
        - "error"
        - "slowquery"
      Engine: "mysql"
      EngineVersion: "8.0.28"
      LicenseModel: "general-public-license"
      MasterUsername: "thanosReg"
      MasterUserPassword: !Ref DBPassword
      OptionGroupName: "default:mysql-8-0"
      Port: "3308"
      PreferredMaintenanceWindow: "sat:10:30-sat:11:00"
      PubliclyAccessible: "false"
      StorageType: "gp2"
      VPCSecurityGroups:
        - "sg-063dde36866c4efb7"
